import { TESTNET_DEPLOYMENT, getDeployment, type Address } from "./deployments";

// ═══════════════════════════════════════════════════════════════
// Contract Addresses
// Auto-populated from deployments.ts (generated by scripts/update-addresses.sh)
// ═══════════════════════════════════════════════════════════════

const ZERO_ADDRESS = "0x0000000000000000000000000000000000000000" as Address;

/**
 * Get all contract addresses for a given chain ID.
 * Falls back to testnet addresses if no deployment found.
 */
export function getContracts(chainId: number = 143) {
  const deployment = getDeployment(chainId);
  if (!deployment) {
    // Fallback to testnet
    return {
      looper: TESTNET_DEPLOYMENT.contracts.core.looper,
      vaultFactory: TESTNET_DEPLOYMENT.contracts.core.vaultFactory,
      vaults: {
        usdcConservative: TESTNET_DEPLOYMENT.contracts.vaults.usdcConservative,
        ethBalanced: ZERO_ADDRESS,
      },
      tokens: {
        WETH: TESTNET_DEPLOYMENT.contracts.mocks.weth,
        USDC: TESTNET_DEPLOYMENT.contracts.mocks.usdc,
        USDT: TESTNET_DEPLOYMENT.contracts.mocks.usdt,
        WBTC: TESTNET_DEPLOYMENT.contracts.mocks.wbtc,
        MON: TESTNET_DEPLOYMENT.contracts.mocks.mon,
      },
      adapters: {
        mace: TESTNET_DEPLOYMENT.contracts.adapters.mace,
        lendingPool: TESTNET_DEPLOYMENT.contracts.mocks.lendingPool,
      },
      mocks: {
        priceOracle: TESTNET_DEPLOYMENT.contracts.mocks.priceOracle,
        dexRouter: TESTNET_DEPLOYMENT.contracts.mocks.dexRouter,
      },
    };
  }

  return {
    looper: deployment.contracts.core.looper,
    vaultFactory: deployment.contracts.core.vaultFactory,
    vaults: {
      usdcConservative: deployment.contracts.vaults.usdcConservative,
      ethBalanced: ZERO_ADDRESS,
    },
    tokens: {
      WETH: deployment.contracts.mocks.weth,
      USDC: deployment.contracts.mocks.usdc,
      USDT: deployment.contracts.mocks.usdt,
      WBTC: deployment.contracts.mocks.wbtc,
      MON: deployment.contracts.mocks.mon,
    },
    adapters: {
      mace: deployment.contracts.adapters.mace,
      lendingPool: deployment.contracts.mocks.lendingPool,
    },
    mocks: {
      priceOracle: deployment.contracts.mocks.priceOracle,
      dexRouter: deployment.contracts.mocks.dexRouter,
    },
  };
}

/** Legacy CONTRACTS export for backward compatibility */
export const CONTRACTS = getContracts(143);

// ABIs — generated from Foundry build artifacts
// These are minimal ABIs for the functions we actually call

export const LOOPER_ABI = [
  {
    name: "whitelistedAssets",
    type: "function",
    stateMutability: "view",
    inputs: [{ name: "asset", type: "address" }],
    outputs: [{ name: "", type: "bool" }],
  },
  {
    name: "whitelistedLendingAdapters",
    type: "function",
    stateMutability: "view",
    inputs: [{ name: "adapter", type: "address" }],
    outputs: [{ name: "", type: "bool" }],
  },
  {
    name: "whitelistedDexAdapters",
    type: "function",
    stateMutability: "view",
    inputs: [{ name: "adapter", type: "address" }],
    outputs: [{ name: "", type: "bool" }],
  },
  {
    name: "loop",
    type: "function",
    stateMutability: "nonpayable",
    inputs: [
      {
        name: "params",
        type: "tuple",
        components: [
          { name: "collateralAsset", type: "address" },
          { name: "debtAsset", type: "address" },
          { name: "amount", type: "uint256" },
          { name: "targetLeverage", type: "uint256" },
          { name: "maxIterations", type: "uint256" },
          { name: "minHealthFactor", type: "uint256" },
          { name: "maxSlippage", type: "uint256" },
          { name: "lendingAdapter", type: "address" },
          { name: "dexAdapter", type: "address" },
        ],
      },
    ],
    outputs: [{ name: "positionId", type: "uint256" }],
  },
  {
    name: "unloop",
    type: "function",
    stateMutability: "nonpayable",
    inputs: [
      { name: "positionId", type: "uint256" },
      { name: "maxSlippage", type: "uint256" },
    ],
    outputs: [{ name: "collateralReturned", type: "uint256" }],
  },
  {
    name: "getPosition",
    type: "function",
    stateMutability: "view",
    inputs: [{ name: "positionId", type: "uint256" }],
    outputs: [
      {
        name: "",
        type: "tuple",
        components: [
          { name: "owner", type: "address" },
          { name: "proxy", type: "address" },
          { name: "collateralAsset", type: "address" },
          { name: "debtAsset", type: "address" },
          { name: "lendingAdapter", type: "address" },
          { name: "dexAdapter", type: "address" },
          { name: "initialCollateral", type: "uint256" },
          { name: "totalCollateral", type: "uint256" },
          { name: "totalDebt", type: "uint256" },
          { name: "targetLeverage", type: "uint256" },
          { name: "initialHealthFactor", type: "uint256" },
          { name: "rebalanceRatioAtCreation", type: "uint256" },
          { name: "emergencyRatioAtCreation", type: "uint256" },
          { name: "createdAt", type: "uint256" },
          { name: "active", type: "bool" },
        ],
      },
    ],
  },
  {
    name: "getPositionsByOwner",
    type: "function",
    stateMutability: "view",
    inputs: [{ name: "owner", type: "address" }],
    outputs: [{ name: "", type: "uint256[]" }],
  },
  {
    name: "getHealthFactor",
    type: "function",
    stateMutability: "view",
    inputs: [{ name: "positionId", type: "uint256" }],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    name: "estimateAPY",
    type: "function",
    stateMutability: "view",
    inputs: [
      { name: "collateralAsset", type: "address" },
      { name: "debtAsset", type: "address" },
      { name: "leverage", type: "uint256" },
      { name: "lendingAdapter", type: "address" },
    ],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    name: "totalPositions",
    type: "function",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
  },
] as const;

export const VAULT_ABI = [
  {
    name: "deposit",
    type: "function",
    stateMutability: "nonpayable",
    inputs: [
      { name: "assets", type: "uint256" },
      { name: "receiver", type: "address" },
    ],
    outputs: [{ name: "shares", type: "uint256" }],
  },
  {
    name: "withdraw",
    type: "function",
    stateMutability: "nonpayable",
    inputs: [
      { name: "assets", type: "uint256" },
      { name: "receiver", type: "address" },
      { name: "owner", type: "address" },
    ],
    outputs: [{ name: "shares", type: "uint256" }],
  },
  {
    name: "redeem",
    type: "function",
    stateMutability: "nonpayable",
    inputs: [
      { name: "shares", type: "uint256" },
      { name: "receiver", type: "address" },
      { name: "owner", type: "address" },
    ],
    outputs: [{ name: "assets", type: "uint256" }],
  },
  {
    name: "totalAssets",
    type: "function",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    name: "balanceOf",
    type: "function",
    stateMutability: "view",
    inputs: [{ name: "account", type: "address" }],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    name: "convertToAssets",
    type: "function",
    stateMutability: "view",
    inputs: [{ name: "shares", type: "uint256" }],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    name: "convertToShares",
    type: "function",
    stateMutability: "view",
    inputs: [{ name: "assets", type: "uint256" }],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    name: "maxDeposit",
    type: "function",
    stateMutability: "view",
    inputs: [{ name: "receiver", type: "address" }],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    name: "depositCap",
    type: "function",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
  },
] as const;

export const ERC20_ABI = [
  {
    name: "balanceOf",
    type: "function",
    stateMutability: "view",
    inputs: [{ name: "account", type: "address" }],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    name: "allowance",
    type: "function",
    stateMutability: "view",
    inputs: [
      { name: "owner", type: "address" },
      { name: "spender", type: "address" },
    ],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    name: "approve",
    type: "function",
    stateMutability: "nonpayable",
    inputs: [
      { name: "spender", type: "address" },
      { name: "amount", type: "uint256" },
    ],
    outputs: [{ name: "", type: "bool" }],
  },
  {
    name: "decimals",
    type: "function",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "uint8" }],
  },
  {
    name: "symbol",
    type: "function",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "string" }],
  },
] as const;

// Mock-specific ABIs for testnet interaction

export const MOCK_ERC20_ABI = [
  ...ERC20_ABI,
  {
    name: "mint",
    type: "function",
    stateMutability: "nonpayable",
    inputs: [
      { name: "to", type: "address" },
      { name: "amount", type: "uint256" },
    ],
    outputs: [],
  },
] as const;

export const MOCK_PRICE_ORACLE_ABI = [
  {
    name: "getPrice",
    type: "function",
    stateMutability: "view",
    inputs: [{ name: "asset", type: "address" }],
    outputs: [{ name: "price", type: "uint256" }],
  },
  {
    name: "setPrice",
    type: "function",
    stateMutability: "nonpayable",
    inputs: [
      { name: "asset", type: "address" },
      { name: "price", type: "uint256" },
    ],
    outputs: [],
  },
  {
    name: "setPrices",
    type: "function",
    stateMutability: "nonpayable",
    inputs: [
      { name: "assets", type: "address[]" },
      { name: "_prices", type: "uint256[]" },
    ],
    outputs: [],
  },
] as const;

export const MOCK_LENDING_POOL_ABI = [
  {
    name: "setRates",
    type: "function",
    stateMutability: "nonpayable",
    inputs: [
      { name: "asset", type: "address" },
      { name: "newSupplyAPY", type: "uint256" },
      { name: "newBorrowAPY", type: "uint256" },
    ],
    outputs: [],
  },
  {
    name: "getSupplyAPY",
    type: "function",
    stateMutability: "view",
    inputs: [{ name: "asset", type: "address" }],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    name: "getBorrowAPY",
    type: "function",
    stateMutability: "view",
    inputs: [{ name: "asset", type: "address" }],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    name: "getCollateralBalance",
    type: "function",
    stateMutability: "view",
    inputs: [
      { name: "account", type: "address" },
      { name: "asset", type: "address" },
    ],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    name: "getDebtBalance",
    type: "function",
    stateMutability: "view",
    inputs: [
      { name: "account", type: "address" },
      { name: "asset", type: "address" },
    ],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    name: "accrueInterest",
    type: "function",
    stateMutability: "nonpayable",
    inputs: [{ name: "account", type: "address" }],
    outputs: [],
  },
  {
    name: "accrueInterestBatch",
    type: "function",
    stateMutability: "nonpayable",
    inputs: [{ name: "accounts", type: "address[]" }],
    outputs: [],
  },
  {
    name: "lastAccrualTime",
    type: "function",
    stateMutability: "view",
    inputs: [{ name: "account", type: "address" }],
    outputs: [{ name: "", type: "uint256" }],
  },
] as const;
