// ═══════════════════════════════════════════════════════════════
// AUTO-GENERATED by scripts/update-addresses.sh
// DO NOT EDIT MANUALLY — re-run the script after deployment.
// Generated: 2026-01-30T00:00:00Z
// ═══════════════════════════════════════════════════════════════

export type Address = `0x${string}`;

export interface DeploymentInfo {
  chainId: number;
  network: string;
  deployer: Address;
  deployedAt: string;
  contracts: {
    mocks: {
      weth: Address;
      usdc: Address;
      usdt: Address;
      wbtc: Address;
      mon: Address;
      priceOracle: Address;
      lendingPool: Address;
      dexRouter: Address;
    };
    core: {
      looper: Address;
      vaultFactory: Address;
    };
    adapters: {
      mace: Address;
    };
    strategies: {
      usdcConservative: Address;
    };
    vaults: {
      usdcConservative: Address;
    };
  };
}

export const TESTNET_DEPLOYMENT: DeploymentInfo = {
  chainId: 10143,
  network: "monad-testnet",
  deployer: "0x9F1536107E2A3146E1f5db587E06A1ea98e6c6a1" as Address,
  deployedAt: "2026-01-30",
  contracts: {
    mocks: {
      weth: "0x1245ee31B06337f361322A0b998De68054a553b4" as Address,
      usdc: "0xb827559A1952b98629e0634cA3622F48812E2A88" as Address,
      usdt: "0x5E94B76c24A180a63F45117FAbAF4547d271BBBA" as Address,
      wbtc: "0xB4B12c46FF63b0680222bCD2e2418685e56D543F" as Address,
      mon: "0xb9508B30a31F92D182624085833e79EA822aE406" as Address,
      priceOracle: "0xCb647234126695d5b3d8686d23ae642e630eaeb5" as Address,
      lendingPool: "0xea44eE41861bF99794C42Cd76cbB108f7Ad81bfb" as Address,
      dexRouter: "0xc0fAA9E57d70f0E45F1ce2Af814595777ecF2962" as Address,
    },
    core: {
      looper: "0x73C8A8Ad454D7E90b37eC77E330df90Afe180635" as Address,
      vaultFactory: "0x05194b89D1f77a9Ea24C01eeC58A2eFeA4a09c9D" as Address,
    },
    adapters: {
      mace: "0xa6a21BE061b25C429EF4F3dc6448c187296A6457" as Address,
    },
    strategies: {
      usdcConservative: "0x4C5ceEb6C4Fc71918020D82C5a01938e5Fcf6621" as Address,
    },
    vaults: {
      usdcConservative: "0x631f0E9B0FdDBD9273962d8e690e11670086dE20" as Address,
    },
  },
};

// Mainnet deployment — Monad mainnet (chain 143)
export const MAINNET_DEPLOYMENT: DeploymentInfo = {
  chainId: 143,
  network: "monad-mainnet",
  deployer: "0xa161A239A629e9684d38AE4a2dc4BAA9aCcE63C2" as Address,
  deployedAt: "2026-02-17",
  contracts: {
    mocks: {
      weth: "0x760AfE86e5de5fa0Ee542fc7B7B713e1c5425701" as Address, // WMON
      usdc: "0x947dD48236C3cBb6f3ee40468235166b7197eAD5" as Address, // USDC on Monad
      usdt: "0x0000000000000000000000000000000000000000" as Address,
      wbtc: "0x0000000000000000000000000000000000000000" as Address,
      mon: "0x0000000000000000000000000000000000000000" as Address, // Native
      priceOracle: "0x0000000000000000000000000000000000000000" as Address,
      lendingPool: "0x876c9Ae0Fde6852160644fEf69B0D31e2D221063" as Address, // NeverlendAdapter (REAL)
      dexRouter: "0x649A0f5D8b214BF72C810Abbe7190cB4670AB6c7" as Address, // MaceAdapter (REAL)
    },
    core: {
      looper: "0xd72d67be2b4b199d1a598a1Ed7B1A7c20c88f7c8" as Address, // LooperLite deployed
      vaultFactory: "0x0000000000000000000000000000000000000000" as Address,
    },
    adapters: {
      mace: "0x649A0f5D8b214BF72C810Abbe7190cB4670AB6c7" as Address, // MaceAdapter (REAL)
    },
    strategies: {
      usdcConservative: "0x0000000000000000000000000000000000000000" as Address,
    },
    vaults: {
      usdcConservative: "0x0000000000000000000000000000000000000000" as Address,
    },
  },
};

// LendingAggregator deployed separately (not part of standard deployment)
export const LENDING_AGGREGATOR = "0x263bF7D5db487B6480CE240DF9347649bd062EFb" as Address;

/**
 * Get the deployment info for a given chain ID.
 * Returns testnet deployment for chain 10143, mainnet for 143.
 */
export function getDeployment(chainId: number): DeploymentInfo | null {
  switch (chainId) {
    case 10143:
      return TESTNET_DEPLOYMENT;
    case 143:
      return MAINNET_DEPLOYMENT;
    default:
      return null;
  }
}
